package com.gobi.util;

import lombok.experimental.UtilityClass;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;

import static org.springframework.http.MediaType.APPLICATION_JSON_VALUE;

@UtilityClass
public class Util {
    public String payrollUrl = "https://interactive.ibi.mn/restapi/";
    public String prodPlmPostUrlToSAP = "http://localhost:8080/api/v1/prodPlm";
    public String plmPostUrlToSAP = "http://localhost:8080/api/v1/plm";
    public String payrollPostUrlToSAP = "http://localhost:8080/api/v1/payroll";

    public HttpHeaders payrollHeaders() {
        HttpHeaders headers = new HttpHeaders();
        headers.setBasicAuth("gobicashmere2o23", "$gob12o23");
        headers.add("X-API-KEY", "69399a188366b8fc8e59b5f0cb127e23a20b65b3");
        return headers;
    }

    public HttpHeaders internalPostHeaders() {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.valueOf(APPLICATION_JSON_VALUE));
        return headers;
    }

    //Material Type Constants - MTART
     public String Auxiliary_Materials_MTART = "11";
     public String Label_MTART = "12";
     public String Chemistry_MTART = "13";
     public String Package_MTART = "14";
     public String Fabrics_MTART = "21";
     public String Prints_MTART = "22";
     public String Embroidery_MTART = "23";
     public String Others_MTART = "19";
     public String Yarn_Coproduct_MTART = "20";
     public String Knit_MTART = "30";
     public String Woven_MTART = "31";
     public String Sewn_MTART = "32";
     public String Custom_Made_MTART = "33";
     public String Raw_Material_Cashmere_MTART = "10";
     public String Raw_Material_Electronic_Etc_MTART = "91";
     public String Semi_Product_MTART = "92";
     public String Services_MTART = "94";


    //Unit Of Measure Constants - MEINS
    public String  Gram_MEINS ="G";
    public String  Kilogram_MEINS ="KG";
    public String  Liter_MEINS ="L";
    public String  Meter_MEINS ="M";
    public String  Square_Meter_MEINS ="M2";
    public String  Cubic_Meter_MEINS ="M3";
    public String  Milligram_MEINS ="MG";
    public String  Bottle_MEINS ="B";
    public String  Centimeter_MEINS ="CM";
    public String  Square_Centimeter_MEINS ="CM2";
    public String  Days_MEINS ="D";
    public String  Degree_MEINS ="DEG";
    public String  Decimeter_MEINS ="DM";
    public String  Dozen_MEINS ="DZ";
    public String GramActive_IngredientLiter_MEINS ="G/L";
    public String GramLiter_MEINS ="GLI";
    public String GramSquare_Meter_MEINS ="GM2";
    public String GramCubic_Meter_MEINS ="GM3";
    public String Gross_MEINS ="GRO";
    public String Hour_MEINS ="H";
    public String Hours_MEINS ="HR";
    public String KilogramGubic_Decimeter_MEINS ="KD3";
    public String KilogramMole_MEINS ="KGM";
    public String KilogramSecond_MEINS ="KGS";
    public String KilogramCubic_Meter_MEINS ="KGV";
    public String OneSquare_Meter_MEINS ="M-2";
    public String MilligramLiter_MEINS ="MIN";
    public String Minute_MEINS ="KGS";
    public String Milliliter_MEINS ="ML";
    public String Millimeter_MEINS ="MM";
    public String Months_MEINS ="MON";
    public String Nanometer_MEINS ="NAM";
    public String Kilonewton_MEINS ="NI";
    public String Pack_MEINS ="PAC";
    public String Piece_MEINS ="PC";
    public String NumberOfPersons_MEINS ="PRS";
    public String Ton_MEINS ="TO";
    public String Thousands_MEINS ="TS";
    public String Weeks_MEINS ="WK";
    public String Years_MEINS ="YR";
    public String Pieces_MEINS ="PCS";

    //Material Groups - MATKL
    public String Polo_MATKL="01";
    public String Cardigan_MATKL = "02";
    public String Top_MATKL = "03";
    public String C_Neck_MATKL = "04";
    public String T_Neck_MATKL = "05";
    public String High_Neck_MATKL = "06";
    public String V_Neck_MATKL = "07";
    public String Dress_MATKL = "08";
    public String Vest_MATKL = "09";
    public String Hat_MATKL = "10";
    public String Socks_MATKL = "11";
    public String Hoodie_MATKL = "12";
    public String Coat_MATKL = "13";
    public String Jacket_MATKL = "14";
    public String Pants_MATKL = "15";
    public String Skirt_MATKL = "16";
    public String Poncho_MATKL = "17";
    public String Short_MATKL = "18";
    public String Gloves_MATKL = "19";
    public String Shawl_MATKL = "20";
    public String Scarf_MATKL_01 = "21";
    public String Warmer_Bag_MATKL = "22";
    public String Blanket_MATKL = "23";
    public String Head_Band_MATKL = "24";
    public String Pillowcase_MATKL = "26";
    public String Bag_MATKL= "27";
    public String Bathrobe_MATKL = "28";
    public String Bralette_BackWarmer_MATKL = "29";
    public String Detail_Swatch_MATKL_01 = "30";
    public String Belt_MATKL = "31";
    public String Leg_Warmer_MATKL = "33";
    public String Baby_Rompers_MATKL = "36";
    public String Scarf_MATKL_02 = "37";
    public String Baby_Shoes_MATKL = "38";
    public String Eye_Mask_MATKL = "41";
    public String Sandals_MATKL = "42";
    public String Baby_Blanket_MATKL = "43";
    public String Necktie_MATKL = "44";
    public String Suits_MATKL = "45";
    public String Fabric_MATKL = "46";
    public String Semi_Worsted_Fabric_MATKL = "47";
    public String Knitted_Fabric_MATKL = "48";
    public String Detail_Swatch_MATKL_02 = "50";
    public String Other_MATKL = "51";
    public String Chair_Cushion_MATKL = "52";
    public String Knee_Warmer_MATKL = "53";
    public String Bed_Runner_MATKL = "54";
    public String Robe_Of_Lama_MATKL = "55";
    public String Comforter_MATKL = "61";
    public String Sleeping_Bag_MATKL = "62";
    public String Topper_MATKL = "63";
    public String Worsted_Fabric_MATKL = "65";
    public String Shoes_MATKL = "66";
    public String Blazer_MATKL = "81";
    public String Trench_Coat_MATKL = "82";
    public String Single_Sided_Fabric_MATKL = "89";
    public String Double_Sided_Fabric_MATKL = "90";
    public String Traditional_Cloth_MATKL = "91";
    public String Traditional_Overdress_MATKL = "92";
    public String Traditional_Vest_MATKL = "93";
    public String Traditional_Topcoat_MATKL = "94";
    public String Traditional_Shirt_MATKL = "95";
    public String Traditional_Clothing_MATKL = "96";
    public String Printed_Scarf_MATKL = "98";
    public String Printed_Shawl_MATKL = "99";
    public String Plumbing_Spare_Parts_MATKL = "Z101";
    public String Electrical_Spare_Parts_MATKL = "Z102";
    public String Electronic_And_Telephone_Spare_Parts_MATKL = "Z103";
    public String Ventilation_Spare_Parts_MATKL = "Z104";
    public String PrimaryWashing_Spare_Parts_MATKL = "Z105";
    public String PrimaryDehairing_Spare_Parts_MATKL = "Z106";
    public String PrimaryPressing_And_SortingSpareParts_MATKL = "Z107";
    public String SpinningSpinningSpareParts_MATKL = "Z108";
    public String SpinningCardingSpareParts_MATKL = "Z109";
    public String SpinningDyeingAndMixingSpareParts_MATKL = "Z110";
    public String SpinningWorsted_Spinning_Spare_Parts_MATKL = "Z111";
    public String WeavingWeaving_Spare_Parts_MATKL = "Z112";
    public String WeavingFinishing_Spare_Parts_MATKL = "Z113";
    public String WeavingPrinting_Spare_Parts_MATKL = "Z114";
    public String KnittingKnitting_Spare_Parts_MATKL = "Z115";
    public String KnittingLinking_And_Finishing_Spare_Parts_MATKL = "Z116";
    public String KnittingWashing_Spare_Parts_MATKL = "Z117";
    public String SewingSpare_Parts_MATKL = "Z118";
    public String DryClean_Spare_Parts_MATKL = "Z119";
    public String Standart_Spare_Parts_MATKL = "Z120";
    public String IT_Spare_Parts_MATKL = "Z121";
    public String Other_Spare_Parts_MATKL = "Z122";
    public String Building_Materials_MATKL = "Z123";
    public String AuxiliaryMaterial_Button_MATKL = "AB";
    public String AuxiliaryMaterial_Buckle_MATKL = "AD";
    public String AuxiliaryMaterial_Fur_MATKL = "AF";
    public String AuxiliaryMaterial_Sticker_MATKL = "AH";
    public String AuxiliaryMaterial_Wing_MATKL = "AI";
    public String AuxiliaryMaterial_Ribbon_MATKL = "AR";
    public String Auxiliary_Material_Sewing_Thread_MATKL = "AS";
    public String AuxiliaryMaterial_Unit_MATKL = "AU";
    public String AuxiliaryMaterial_Woven_MATKL = "AW";
    public String AuxiliaryMaterial_Zipper_MATKL = "AZ";
    public String Chemical_Chemical_MATKL = "CC";
    public String Chemical_Dye_MATKL = "CD";
    public String Label_CareLabel_MATKL = "LC";
    public String Label_WovenLabel_MATKL = "LE";
    public String Label_Label_MATKL = "LL";
    public String Other_Fur_MATKL = "OF";
    public String Other_Other_MATKL = "OO";
    public String Other_Ribbon_MATKL = "OR";
    public String Other_OtherThread_MATKL = "OT";
    public String Other_Unit_MATKL = "OU";
    public String Other_Woven_MATKL = "OW";
    public String Package_Grid_MATKL = "PG";
    public String Package_Hanger_MATKL = "PJ";
    public String Package_Daavuu_drap = "PM";
    public String Package_N_MATKL = "PN";
    public String Package_Other_MATKL = "PO";
    public String Package_Press_MATKL = "PP";
    public String Package_Tape_MATKL = "PV";
    public String Package_Box_MATKL = "PX";
    public String Package_Bag_MATKL = "PY";
    public String Yarn_Knitting_MATKL = "YK";
    public String Yarn_Woven_MATKL = "YW";
    public String Dry_Cleaning_MATKL = "Z201";
    public String Wet_Cleaning_MATKL = "Z202";
    public String Repairing_MATKL = "Z203";
    public String Made_Custom_MATKL = "Z204";
    public String Spare_Parts_MATKL = "Z1";
    public String Service_MATKL = "Z2";
    public String Plumbing_Service_MATKL = "Z251";
    public String Electrical_Service_MATKL = "Z252";
    public String Electronic_And_Telephone_Service_MATKL = "Z253";
    public String Ventilation_Service_MATKL = "Z254";
    public String Building_Service_MATKL = "Z255";
    public String Equipment_Service_MATKL = "Z256";
    public String Equipment_Rent_Service_MATKL = "Z257";
    public String Semi_Product_MATKL = "Z3";
    public String By_Product_MATKL = "Z301";
    public String Stationery_Material_MATKL = "OS";
    public String Cleaning_Material_MATKL = "OC";
    public String Safety_Material_MATKL = "OM";
    public String Supply_Other_Material_MATKL = "SO";
    public String Utility_Material_MATKL = "UM";


    //Laboratory/design office(Category) - LABOR
    public String Knitted_Sweater_LABOR = "01";
    public String Knitted_Cardigan_LABOR = "02";
    public String Knitted_Pants_LABOR = "03";
    public String Knitted_Scarf_Shawl_LABOR = "04";
    public String Knitted_Hat_LABOR = "05";
    public String Knitted_Poncho_LABOR = "06";
    public String Knitted_Gloves_LABOR = "07";
    public String Knitted_Socks_LABOR = "08";
    public String Knitted_Skirt_LABOR = "09";
    public String Knitted_Blanket_LABOR  = "10";
    public String Knitted_Other_LABOR = "11";
    public String Sewn_Coat_LABOR = "12";
    public String Sewn_Blazer_LABOR  = "13";
    public String Sewn_Jacket_LABOR = "14";
    public String Sewn_Trench_Coat_LABOR = "15";
    public String Sewn_Pants_LABOR = "16";
    public String Sewn_Other_LABOR = "17";
    public String Woven_Shawl_LABOR = "18";
    public String Woven_Scarf_LABOR = "19";
    public String Woven_Blanket_LABOR = "20";
    public String Woven_Other_LABOR = "21";
    public String FabricOne_TwoSided_LABOR = "22";
    public String Fabric_LABOR = "23";
    public String Yarn_Knitting_LABOR = "24";
    public String Yarn_Woven_LABOR = "25";
    public String Dehaired_Cashmere_LABOR = "26";
    public String RawCashmere_Sorted_LABOR = "27";
    public String RawCashmere_WIP_LABOR = "28";
    public String RawMaterial_ByProduct_LABOR = "29";
    public String Auxiliary_LABOR = "30";
    public String Chemical_LABOR = "31";
    public String Package_LABOR = "32";
    public String Knitted_Footwear_LABOR = "41";
    public String Sewn_Hat_LABOR = "51";
    public String Sewn_Footwear_LABOR = "52";
    public String Woven_Screen_Printed_Shawl_LABOR = "61";
    public String BuildingMaterials_SparePart_LABOR = "98";
    public String Other_LABOR = "99";


    //Division - SPART
    public String General_SPART = "00";
    public String Knitting_SPART = "10";
    public String Sewing_SPART = "20";
    public String Woven_SPART = "30";
    public String Other_SPART = "40";


    //External Material Group Brand code - EXTWG
    public String Bel_Cashmere_EXTWG = "01";
    public String Black_Goat_EXTWG = "02";
    public String Cashmika_EXTWG = "03";
    public String Gobi_Cashmere_EXTWG = "04";
    public String Gobi_Organic_Mongolian_Cashmere_EXTWG = "05";
    public String Goyo_EXTWG = "06";
    public String Goyo_Kids_EXTWG = "07";
    public String Harriss_Grace_EXTWG = "08";
    public String Herders_EXTWG = "09";
    public String Kids_EXTWG = "10";
    public String Leret_EXTWG = "11";
    public String Moonbat_EXTWG = "12";
    public String Nomadico_Cashmere_EXTWG = "13";
    public String ODM_Other_EXTWG = "14";
    public String Oyuna_EXTWG = "15";
    public String Sodgerel_EXTWG = "16";
    public String TDV_EXTWG = "17";
    public String YAMA_EXTWG = "18";

}
